version: 1
formatters:
  simple:
    format: '%(module)s %(funcName)s %(levelname)s - %(message)s'
handlers:
  syslog:
    class: logging.handlers.SysLogHandler
    formatter: simple
    address: /dev/log
    facility: local7
loggers:
  pmworker:
    level: INFO
    handlers: [syslog]
    propagate: yes
  celery:
    level: INFO
    handlers: [syslog]
    propagate: yes
root:
  level: INFO
  handlers: [syslog]
  propagate: yes
